package dmit2015.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.io.Serializable;
import java.time.LocalDateTime;

@Entity
@Table(name = "BeerMultiUser")
@Getter @Setter
@NoArgsConstructor
public class Beer implements Serializable {

    @Column(nullable = false, length = 32)
    private String username;

    @Id                 // This is the primary key field
    @GeneratedValue(strategy = GenerationType.IDENTITY)     // This primary key field is generated by the database
    private Long id;

    @NotBlank(message = "Task cannot be blank.")
    @Column(nullable = false, length = 64)
    private String task;


    @NotBlank(message = "Name cannot be blank.")
    @Column(nullable = false, length = 64)
    private String name;
    @NotBlank(message = "Style cannot be blank.")
    @Column(nullable = false, length = 64)
    private String style;
    @NotBlank(message = "Brand cannot be blank.")
    @Column(nullable = false, length = 64)
    private String brand;



    private boolean done;

    @Version
    private Integer version;

    @Column(nullable = false)
    private LocalDateTime createTime;

    private LocalDateTime updateTime;

    @PrePersist
    private void beforePersist() {
        createTime = LocalDateTime.now();
    }

    @PreUpdate
    private void beforeUpdate() {
        updateTime = LocalDateTime.now();
    }

    public Beer(Long id, String task, boolean done,String name, String style, String brand) {
        this.id = id;
        this.task = task;
        this.name = name;
        this.style = style;
        this.brand = brand;
        this.done = done;
    }

}